.TH pass-vera 1 "March 2021" "pass-vera"

.SH NAME
pass-vera \- A \fBpass\fP(1) extension that adds another layer of encryption
by encrypting the password-store inside a \fBveracrypt\fP(1) drive.

.SH SYNOPSIS
\fBpass vera\fP [\fB-k\fP | \fB--tmp-key\fP] [\fB-n\fP] [\fB-o\fP] [\fB-p\fP \fIpath\fP] [\fB-q\fP | \fB-v\fP] [\fB-r\fP] [\fB-s\fP] [\fB-t\fP \fItime\fP] \fI<gpg-id>\fP
.br
\fBpass open\fP [\fB-f\fP] [\fB-q\fP | \fB-v\fP] [\fB-r\fP] [\fB-t\fP \fItime\fP]
.br
\fBpass close\fP [\fB-f\fP] [\fB-q\fP | \fB-v\fP]

.SH DESCRIPTION
Due to the structure of \fBpass\fP(1), file and directory names are not encrypted
in the password store. \fBpass vera\fP provides a convenient solution to put one's
password store in an encrypted drive with \fBveracrypt\fP(1) and then keep the
password tree encrypted when it is not being used.

It uses the same GPG key (by default) to encrypt passwords and the veracrypt drive,
therefore one doesn't need to manage another key. Moreover, pass-vera can be given
a timer to automatically close the password store after a given time.

.TP
.B BEFORE USING THIS PROGRAM:
Make a backup of your password-store directory. Once the vera is created, move the
backup to the location of the mounted drive.

.TP
.B WORKFLOW
.IP
\fB(1)\fP Create a password vera with \fBpass vera\fP <\fIgpg-id\fP>. Type anything in the text file
that opens (make sure to remember it). One will then be prompted for a password to be
entered (it does not have to be the same as the text file). The "vera", is created and
mounted in \fIPASSWORD_STORE_DIR\fP (or, if unset, then \fI~/.password-store\fP). Finally,
the newly created drive will be initialized as a password-store using the same GPG key.

The \fItext file\fP that is created is used as a keyfile to the vera. It works by
encrypting the key using GPG when it is not being used, and decrypting the key at
the time of mounting/using \fBpass open\fP.

.IP
\fB(2)\fP If you have \fIPASSWORD_STORE_DIR\fP set, copy the backup of the password store to this
location, otherwise copy it to \fI~/.password-store\fP. Now, use pass as usual.
.IP
\fB(3)\fP When finished, close the password vera: \fBpass close\fP.
.IP
\fB(4)\fP To use pass again, open the password vera: \fBpass open\fP.


.SH COMMAND

.TP
\fBpass vera\fP [ \fB--no-init\fP, \fB-n\fP ] [\fB--timer\fP=\fItime\fP, \fB-t\fP \fItime\fP]
   [ \fB--path\fP=\fIsubfolder\fP, \fB-p\fP \fIsubfolder\fP ] [\fB--truecrypt\fP, \fB-r\fP]
   [\fB--vera-key\fP, \fB-k\fP] [\fB--overwrite-key\fP, \fB-o\fP] [\fB--tmp-key\fP]
   [\fB--force\fP, \fB-f\fP] [\fB--status\fP, \fB-s\fP] \fI<gpg-id>\fP

Create and initialize a new password vera. This command must be run first,
before a password store can be used. The user will be prompted with a blank text
document where anything can be entered (be sure to remember it), and then prompted
again to enter a password that will encrypt the veracrypt drive.

If no key type is given (\fB--vera-key\fP or \fB--tmp-key\fP) then the blank text
document that was prompted will be encrypted, and the decrypted version of that file
will be used as the key for the vera. The key will remain encrypted until the user
opens the vera, and then once the key has finished its purpose it will be re-encrypted.
If this key is lost, all the data within the vera will not be accessible.

Use \fIgpg-id\fP for the encryption of both passwords and vera. Multiple gpg-ids
may be specified to encrypt the vera and each password with multiple ids.

If \fB--no-init\fP, \fB-n\fP is specified, the password store is not initialized.
By default, pass-vera initializes the password store with the same key(s) that
generated the vera. The purpose of this option is to give the user the option to
initialize the password store with a different key or set of keys.

If \fB--timer\fP, \fB-t\fP is specified, along with a \fItime\fP argument, the password
store will automatically close using a \fBlaunchctl\fP(1) agent that runs a script
after a given time. The agent will be unloaded once the pass vera is closed dismounted,
and a notification will be sent using osascript.

.TP
.B TIMER FORMAT
Must match one of the following:
.IP
.br
  \fB(1)\fP "1 hour 5 minutes"      \fB(2)\fP "1hour 5minutes"
.IP
.br
  \fB(3)\fP "1 hr 5 mins"           \fB(4)\fP "1hr 5mins"
.IP
.br
  \fINote\fP: An hour is not required when specifying time. Also, if both an
.br
  hour and minute are specified, place the parameter in quotation marks. The
.br
  only reason why one would not ever quote the parameter is if something like
.br
  1hr is given.

If \fB--path\fP or \fB-p\fP is specified, along with a \fIsubfolder\fP,
a specific password vera using the given gpg-id or a given set of gpg-ids is
assigned to that specific subfolder of the password store.

If \fB--truecrypt\fP or \fB-r\fP is specified, the vera will have enabled TrueCrypt
compatibility mode to permit the mouting of volumes that were created using TrueCrypt
versions 6.x or 7.x. This option can be used by setting the \fIPASSWORD_STORE_VERA_FILE\fP
environment variable to a file that is used by TrueCrypt.

If \fB--vera-key\fP or \fB-k\fP is specified, /dev/urandom will be used to create
a key specifically for the vera drive. This is stored in your home folder and is specified
by the \fIPASSWORD_STORE_VERA_KEY\fP environment variable. If this key is lost, all the data
within the vera will not be accessible.

If \fB--overwrite-key\fP or \fB-o\fP is specified, the existing key that is used
by pass vera to mount the drive will be overwritten with the new kind of key that
is specified. This option should be used only whenever one is having some sort of
issue setting pass-vera up, and has backed up all of the data on the existing vera drive.

If \fB--tmp-key\fP is specified, a one-time key will be created and all data that is
placed within this drive while it is mounted will no longer be accessible when the
drive is dismounted.

If \fB--force\fP is specified, the password vera will create or mount the
password store to a volume that is in use, or it will force dismount a volume
that is in use. This can also overwrite files, so use cautiously.

If \fB--status\fP or \fB-s\fP is specified, the status of the vera (mounted or not)
will be printed on the screen.

.TP
\fBpass open\fP [\fB--timer\fP=\fItime\fP, \fB-t\fP \fItime\fP] [\fB--truecrypt\fP, \fB-r\fP] [\fB--force\fP, \fB-f\fP] [\fIsubfolder\fP]

Open a password vera. If a \fItime\fP parameter is given (e.g., 1 hour 5 minutes)
then a launchctl agent will be loaded. After the specified time interval,
a script will run that will dismount the drive and unload the agent.

.TP
.B ADD MULTIPLE TIMERS
If \fB--timer\fP, \fB-t\fP is specified, along with \fItime\fP argument, the password
store will be automatically closed using a launchctl agent that runs a script
after a given time. If a '.timer' file was already present in the store, this time
will be updated, which updates the launchctl agent. Therefore, multiple timers can be
passed, one extending upon the next.

For example, if you open the password vera
using \fBpass open --timer=\fP\fI5 minutes\fP, and then one minute later decide
to add more time to the already running timer using \fBpass open --timer=\fP\fI2 minutes\fP,
the password vera will close in 6 minutes.

If \fB--force\fP is specified, the password vera will create or mount the
password store to a volume that is in use, or it will force dismount a volume
that is in use. This can also overwrite files, so use cautiously.

If \fIsubfolder\fP is specified, the password store will be opened in the subfolder.
Otherwise, pass vera will open in \fIPASSWORD_STORE_DIR\fP if set, and if not, then
it will open in \fI~/.password-store\fP.

.TP
\fBpass close\fP [\fB--force\fP, \fB-f\fP] [\fIstore\fP]
Close a password vera.

If \fB--force\fP is specified, the password vera will create or mount the
password store to a volume that is in use, or it will force dismount a volume
that is in use. This can also overwrite files, so use cautiously.

If \fIstore\fP is specified, pass close will try to close this store. Otherwise, pass
close will close the the vera opened at \fIPASSWORD_STORE_DIR\fP or \fI~/.password-store\fP.

.SH OPTIONS
.TP
\fB\-n\fB, \-\-no-init\fR
Do not initialize the password store

.TP
\fB\-t\fB, \-\-timer\fR
Close the store after a given time

.TP
\fB\-p\fB, \-\-path\fR
Create the store for that specific subfolder

.TP
\fB\-r\fB, \-\-truecrypt\fR
Enable compatiblity with TrueCrypt

.TP
\fB\-k\fB, \-\-vera\-key\fR
Create a key with /dev/urandom instead of GPG

.TP
\fB\-o\fB, \-\-overwrite\-key\fR
Overwrite existing key in favor of the one specified

.TP
\fB\-\-tmp\-key\fR
Create a one-time key for a one-time accessible vera

.TP
\fB\-f\fB, \-\-force\fR
Force the vera operations (i.e. even if mounted volume is in use)

.TP
\fB\-s\fB, \-\-status\fR
Show status of pass vera, (i.e., open or closed)

.TP
\fB\-q\fB, \-\-quiet\fR
Be quiet

.TP
\fB\-v\fB, \-\-verbose\fR
Be verbose

.TP
\fB\-d\fB, \-\-debug\fR
Enable debugging of the launch agent. The path of the stderr file will
be \fI$HOME/pass-vera-stderr.log\fP and the path of the stdout file will be
\fI$HOME/pass-vera-stdout.log\fP

.TP
\fB\-\-unsafe\fR
Does not encrypt free space when creating a device-hosted volume

.TP
\fB\-V\fB, \-\-version\fR
Show version information

.TP
\fB\-h\fB, \-\-help\fR
Show usage message


.SH EXAMPLES

.TP
Create a new password vera
.B zx2c4@laptop ~ $ pass vera Jason@zx2c4.com
.br
 (*) GPG key created
.br
  Enter password:
.br
  Done: 100.000%  Speed: 4.6 MiB/s  Left: 0 s
.br
  The VeraCrypt volume has been successfully created.
.br
  Enter password for ~/.password.vera
.br
 (*) Your password vera has been created and opened in ~/.password-store.
.br
 (*) Password store initialized for Jason@zx2c4.com.
.br
  .  Your vera is: ~/.password.vera
.br
  .  Your vera key is: ~/.password.key.vera
.br
  .  You can now use pass as usual.
.br
  .  When finished, close the password vera using 'pass close'.

.TP
Open a password vera
.B zx2c4@laptop ~ $ pass open
.br
  Enter password for ~/.password.vera:
.br
 (*) Your password vera has been opened in ~/.password-store.
.br
  .  You can now use pass as usual.
.br
  .  When finished, close the password vera using 'pass close'.

.TP
Close a password vera
.B zx2c4@laptop ~ $ pass close
.br
 (*) Your password vera has been closed.
.br
  .  Your passwords remain present in ~/.password.vera.

.TP
Create a new password vera and set a timer
.B zx2c4@laptop ~ $ pass vera Jason@zx2c4.com --timer="1 hour"
.br
 (*) GPG key created
.br
  Enter password for ~/.password-store
.br
 (*) pass-close.password.vera.plist loaded
.br
 (*) Your password vera has been created and opened in ~/.password-store.
.br
 (*) Password store initialized for Jason@zx2c4.com.
.br
  .  Your vera is: ~/.password.vera
.br
  .  Your vera key is: ~/.password.key.vera
.br
  .  You can now use pass as usual.
.br
  .  This password store will be closed in: 1 hour
.br
.B zx2c4@laptop ~ $ pass open
.br
  w  The veracrypt drive is already mounted, not opening
.br
 (*) Your password vera has been opened in ~/.password-store.
.br
  .  You can now use pass as usual.
.br
  .  When finished, close the password vera using 'pass close'.

.TP
Open a password vera and set a timer and add additional time after 5 minutes pass by
.B zx2c4@laptop ~ $ pass open --timer="10 minutes"
.br
  Enter password for ~/.password.vera
.br
 (*) pass-close.password.vera.plist loaded
.br
 (*) Your password vera has been opened in ~/.password-store.
.br
  .  You can now use pass as usual.
.br
  .  This password store will be closed in: 10 minutes
.br
.B zx2c4@laptop ~ $ pass open --timer="10 minutes"
.br
  w  The veracrypt drive is already mounted, not opening
.br
 (*) pass-close.password.vera.plist timer has been updated
.br
 (*) Your password vera has been opened in ~/.password-store.
.br
  .  You can now use pass as usual.
.br
  .  This password store will be closed in: 15 minutes


.SH ENVIRONMENT VARIABLES
.TP
.I PASSWORD_STORE_VERA
Path to veracrypt executable
.TP
.I PASSWORD_STORE_VERA_FILE
Path to the password vera, by default \fI~/.password.vera\fP
.TP
.I PASSWORD_STORE_VERA_KEY
Path to the password vera key file by default \fI~/.password.key.vera\fP
.TP
.I PASSWORD_STORE_VERA_SIZE
Password vera size in MB, by default \fI10\fP


.SH SEE ALSO
.BR pass(1),
.BR veracrypt(1),
.BR launchctl(1),
.BR pass-clip(1)
.BR pass-ssh(1),
.BR pass-import(1),
.BR pass-otp(1)

.SH AUTHORS
.B pass vera
.ME .
was written by
.MT lucas@burnsac.xyz
Lucas Burns
.ME .

.SH COPYING
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
